### PR TITLE
add .travis.yml

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Review by nbronson — COMMENTED** [review]
Is the find | xargs rm standard practice with travis? It seems very risky

**Comment by xuwei-k** [comment]
removed cache settings

**Comment by Sciss** [comment]
Please move the request to https://github.com/scala-stm/scala-stm/ - you should use `test:test` now.

**Comment by xuwei-k** [comment]
Why not transfer? https://help.github.com/articles/about-repository-transfers/

**Pull request closed without merging**
