### PR TITLE
Support Scala 2.13.0-M2

### PR DESCRIPTION
**Pull request by marcospereira**

### CODE REVIEW

**Comment by nbronson** [comment]
Thank you!

**Comment by marcospereira** [comment]
Thanks for the fast feedback here, @nbronson.

Could you please a release here?

**Comment by nbronson** [comment]
I'm traveling and don't have the keys with me to do a release this week, sorry. I should be able to do it next Monday

**Comment by marcospereira** [comment]
Thank you for the heads up, @nbronson!

**Comment by marcospereira** [comment]
Hi @nbronson sorry for bumping this again you here, but do you think we can have a release for 2.13.0-M2?

Thanks.

**Comment by nbronson** [comment]
It's on maven central now.

**Pull request merged**
